name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  pull_code:
    name: Pull code from Git
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app/furnitureWebsite
            git pull origin main

  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: pull_code

    steps:
      - name: Rebuild and deploy code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            docker compose stop frontend
            docker compose up -d frontend --build
            docker image prune -f

  notify_email:
    name: Notify email
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Notify email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          to: ${{secrets.MAIL_TO}}
          from: Comfysloth Deployment[bot]
          subject: 'Re:[${{github.repository}}] ${{ github.event.head_commit.message }}'
          body: 'Successfully deployed to the followings URL: ${{secrets.APP_DEPLOY_URL}}'
